Search.setIndex({
  alltitles: {
    "Contents:": [[0, null]],
    "Indices and tables": [[0, "indices-and-tables"]],
    MatchFlow: [
      [2, null],
      [3, null],
    ],
    "MatchFlow Tools Documentation": [[0, null]],
    "Module Index": [[1, null]],
  },
  docnames: [
    "index",
    "module",
    "module_stubs/matchflow",
    "module_stubs/MatchFlow",
  ],
  envversion: {
    sphinx: 65,
    "sphinx.domains.c": 3,
    "sphinx.domains.changeset": 1,
    "sphinx.domains.citation": 1,
    "sphinx.domains.cpp": 9,
    "sphinx.domains.index": 1,
    "sphinx.domains.javascript": 3,
    "sphinx.domains.math": 2,
    "sphinx.domains.python": 4,
    "sphinx.domains.rst": 2,
    "sphinx.domains.std": 2,
    "sphinx.ext.viewcode": 1,
  },
  filenames: [
    "index.rst",
    "module.rst",
    "module_stubs/matchflow.rst",
    "module_stubs/MatchFlow.rst",
  ],
  indexentries: {
    "a_attr (matchflow.feature property)": [
      [2, "MatchFlow.Feature.a_attr", false],
      [3, "MatchFlow.Feature.a_attr", false],
    ],
    "apply_matcher() (in module matchflow)": [
      [2, "MatchFlow.apply_matcher", false],
      [3, "MatchFlow.apply_matcher", false],
    ],
    "b_attr (matchflow.feature property)": [
      [2, "MatchFlow.Feature.b_attr", false],
      [3, "MatchFlow.Feature.b_attr", false],
    ],
    "build() (matchflow.feature method)": [
      [2, "MatchFlow.Feature.build", false],
      [3, "MatchFlow.Feature.build", false],
    ],
    "build_from_doc_freqs() (matchflow.vectorizer method)": [
      [2, "MatchFlow.Vectorizer.build_from_doc_freqs", false],
      [3, "MatchFlow.Vectorizer.build_from_doc_freqs", false],
    ],
    "clilabeler (class in matchflow)": [
      [2, "MatchFlow.CLILabeler", false],
      [3, "MatchFlow.CLILabeler", false],
    ],
    "create_features() (in module matchflow)": [
      [2, "MatchFlow.create_features", false],
      [3, "MatchFlow.create_features", false],
    ],
    "create_seeds() (in module matchflow)": [
      [2, "MatchFlow.create_seeds", false],
      [3, "MatchFlow.create_seeds", false],
    ],
    "cross_val_scores() (matchflow.sklearnmodel method)": [
      [2, "MatchFlow.SKLearnModel.cross_val_scores", false],
      [3, "MatchFlow.SKLearnModel.cross_val_scores", false],
    ],
    "customlabeler (class in matchflow)": [
      [2, "MatchFlow.CustomLabeler", false],
      [3, "MatchFlow.CustomLabeler", false],
    ],
    "down_sample() (in module matchflow)": [
      [2, "MatchFlow.down_sample", false],
      [3, "MatchFlow.down_sample", false],
    ],
    "entropy() (matchflow.mlmodel method)": [
      [2, "MatchFlow.MLModel.entropy", false],
      [3, "MatchFlow.MLModel.entropy", false],
    ],
    "entropy() (matchflow.sklearnmodel method)": [
      [2, "MatchFlow.SKLearnModel.entropy", false],
      [3, "MatchFlow.SKLearnModel.entropy", false],
    ],
    "entropy() (matchflow.sparkmlmodel method)": [
      [2, "MatchFlow.SparkMLModel.entropy", false],
      [3, "MatchFlow.SparkMLModel.entropy", false],
    ],
    "feature (class in matchflow)": [
      [2, "MatchFlow.Feature", false],
      [3, "MatchFlow.Feature", false],
    ],
    "featurize() (in module matchflow)": [
      [2, "MatchFlow.featurize", false],
      [3, "MatchFlow.featurize", false],
    ],
    "get_base_sim_functions() (in module matchflow)": [
      [2, "MatchFlow.get_base_sim_functions", false],
      [3, "MatchFlow.get_base_sim_functions", false],
    ],
    "get_base_tokenizers() (in module matchflow)": [
      [2, "MatchFlow.get_base_tokenizers", false],
      [3, "MatchFlow.get_base_tokenizers", false],
    ],
    "get_extra_tokenizers() (in module matchflow)": [
      [2, "MatchFlow.get_extra_tokenizers", false],
      [3, "MatchFlow.get_extra_tokenizers", false],
    ],
    "get_model() (matchflow.sklearnmodel method)": [
      [2, "MatchFlow.SKLearnModel.get_model", false],
      [3, "MatchFlow.SKLearnModel.get_model", false],
    ],
    "get_model() (matchflow.sparkmlmodel method)": [
      [2, "MatchFlow.SparkMLModel.get_model", false],
      [3, "MatchFlow.SparkMLModel.get_model", false],
    ],
    "goldlabeler (class in matchflow)": [
      [2, "MatchFlow.GoldLabeler", false],
      [3, "MatchFlow.GoldLabeler", false],
    ],
    "init() (matchflow.vectorizer method)": [
      [2, "MatchFlow.Vectorizer.init", false],
      [3, "MatchFlow.Vectorizer.init", false],
    ],
    "label_data() (in module matchflow)": [
      [2, "MatchFlow.label_data", false],
      [3, "MatchFlow.label_data", false],
    ],
    "label_pair() (matchflow.customlabeler method)": [
      [2, "MatchFlow.CustomLabeler.label_pair", false],
      [3, "MatchFlow.CustomLabeler.label_pair", false],
    ],
    "label_pairs() (in module matchflow)": [
      [2, "MatchFlow.label_pairs", false],
      [3, "MatchFlow.label_pairs", false],
    ],
    "labeler (class in matchflow)": [
      [2, "MatchFlow.Labeler", false],
      [3, "MatchFlow.Labeler", false],
    ],
    "load_dataframe() (in module matchflow)": [
      [2, "MatchFlow.load_dataframe", false],
      [3, "MatchFlow.load_dataframe", false],
    ],
    "load_features() (in module matchflow)": [
      [2, "MatchFlow.load_features", false],
      [3, "MatchFlow.load_features", false],
    ],
    matchflow: [
      [2, "module-MatchFlow", false],
      [3, "module-MatchFlow", false],
    ],
    "mlmodel (class in matchflow)": [
      [2, "MatchFlow.MLModel", false],
      [3, "MatchFlow.MLModel", false],
    ],
    module: [
      [2, "module-MatchFlow", false],
      [3, "module-MatchFlow", false],
    ],
    "nan_fill (matchflow.mlmodel attribute)": [
      [2, "MatchFlow.MLModel.nan_fill", false],
      [3, "MatchFlow.MLModel.nan_fill", false],
    ],
    "nan_fill (matchflow.mlmodel property)": [
      [2, "id0", false],
      [3, "id0", false],
    ],
    "nan_fill (matchflow.sklearnmodel property)": [
      [2, "MatchFlow.SKLearnModel.nan_fill", false],
      [3, "MatchFlow.SKLearnModel.nan_fill", false],
    ],
    "nan_fill (matchflow.sparkmlmodel property)": [
      [2, "MatchFlow.SparkMLModel.nan_fill", false],
      [3, "MatchFlow.SparkMLModel.nan_fill", false],
    ],
    "out_col_name() (matchflow.tokenizer method)": [
      [2, "MatchFlow.Tokenizer.out_col_name", false],
      [3, "MatchFlow.Tokenizer.out_col_name", false],
    ],
    "out_col_name() (matchflow.vectorizer method)": [
      [2, "MatchFlow.Vectorizer.out_col_name", false],
      [3, "MatchFlow.Vectorizer.out_col_name", false],
    ],
    "params_dict() (matchflow.mlmodel method)": [
      [2, "MatchFlow.MLModel.params_dict", false],
      [3, "MatchFlow.MLModel.params_dict", false],
    ],
    "params_dict() (matchflow.sklearnmodel method)": [
      [2, "MatchFlow.SKLearnModel.params_dict", false],
      [3, "MatchFlow.SKLearnModel.params_dict", false],
    ],
    "params_dict() (matchflow.sparkmlmodel method)": [
      [2, "MatchFlow.SparkMLModel.params_dict", false],
      [3, "MatchFlow.SparkMLModel.params_dict", false],
    ],
    "predict() (matchflow.mlmodel method)": [
      [2, "MatchFlow.MLModel.predict", false],
      [3, "MatchFlow.MLModel.predict", false],
    ],
    "predict() (matchflow.sklearnmodel method)": [
      [2, "MatchFlow.SKLearnModel.predict", false],
      [3, "MatchFlow.SKLearnModel.predict", false],
    ],
    "predict() (matchflow.sparkmlmodel method)": [
      [2, "MatchFlow.SparkMLModel.predict", false],
      [3, "MatchFlow.SparkMLModel.predict", false],
    ],
    "predict_with_confidence() (matchflow.mlmodel method)": [
      [2, "MatchFlow.MLModel.predict_with_confidence", false],
      [3, "MatchFlow.MLModel.predict_with_confidence", false],
    ],
    "predict_with_confidence() (matchflow.sklearnmodel method)": [
      [2, "MatchFlow.SKLearnModel.predict_with_confidence", false],
      [3, "MatchFlow.SKLearnModel.predict_with_confidence", false],
    ],
    "predict_with_confidence() (matchflow.sparkmlmodel method)": [
      [2, "MatchFlow.SparkMLModel.predict_with_confidence", false],
      [3, "MatchFlow.SparkMLModel.predict_with_confidence", false],
    ],
    "prediction_conf() (matchflow.mlmodel method)": [
      [2, "MatchFlow.MLModel.prediction_conf", false],
      [3, "MatchFlow.MLModel.prediction_conf", false],
    ],
    "prediction_conf() (matchflow.sklearnmodel method)": [
      [2, "MatchFlow.SKLearnModel.prediction_conf", false],
      [3, "MatchFlow.SKLearnModel.prediction_conf", false],
    ],
    "prediction_conf() (matchflow.sparkmlmodel method)": [
      [2, "MatchFlow.SparkMLModel.prediction_conf", false],
      [3, "MatchFlow.SparkMLModel.prediction_conf", false],
    ],
    "prep_fvs() (matchflow.mlmodel method)": [
      [2, "MatchFlow.MLModel.prep_fvs", false],
      [3, "MatchFlow.MLModel.prep_fvs", false],
    ],
    "preprocess() (matchflow.feature method)": [
      [2, "MatchFlow.Feature.preprocess", false],
      [3, "MatchFlow.Feature.preprocess", false],
    ],
    "preprocess_output_column() (matchflow.feature method)": [
      [2, "MatchFlow.Feature.preprocess_output_column", false],
      [3, "MatchFlow.Feature.preprocess_output_column", false],
    ],
    "save_dataframe() (in module matchflow)": [
      [2, "MatchFlow.save_dataframe", false],
      [3, "MatchFlow.save_dataframe", false],
    ],
    "save_features() (in module matchflow)": [
      [2, "MatchFlow.save_features", false],
      [3, "MatchFlow.save_features", false],
    ],
    "sklearnmodel (class in matchflow)": [
      [2, "MatchFlow.SKLearnModel", false],
      [3, "MatchFlow.SKLearnModel", false],
    ],
    "sparkmlmodel (class in matchflow)": [
      [2, "MatchFlow.SparkMLModel", false],
      [3, "MatchFlow.SparkMLModel", false],
    ],
    "template() (matchflow.feature class method)": [
      [2, "MatchFlow.Feature.template", false],
      [3, "MatchFlow.Feature.template", false],
    ],
    "tokenize() (matchflow.tokenizer method)": [
      [2, "MatchFlow.Tokenizer.tokenize", false],
      [3, "MatchFlow.Tokenizer.tokenize", false],
    ],
    "tokenize_set() (matchflow.tokenizer method)": [
      [2, "MatchFlow.Tokenizer.tokenize_set", false],
      [3, "MatchFlow.Tokenizer.tokenize_set", false],
    ],
    "tokenize_spark() (matchflow.tokenizer method)": [
      [2, "MatchFlow.Tokenizer.tokenize_spark", false],
      [3, "MatchFlow.Tokenizer.tokenize_spark", false],
    ],
    "tokenizer (class in matchflow)": [
      [2, "MatchFlow.Tokenizer", false],
      [3, "MatchFlow.Tokenizer", false],
    ],
    "train() (matchflow.mlmodel method)": [
      [2, "MatchFlow.MLModel.train", false],
      [3, "MatchFlow.MLModel.train", false],
    ],
    "train() (matchflow.sklearnmodel method)": [
      [2, "MatchFlow.SKLearnModel.train", false],
      [3, "MatchFlow.SKLearnModel.train", false],
    ],
    "train() (matchflow.sparkmlmodel method)": [
      [2, "MatchFlow.SparkMLModel.train", false],
      [3, "MatchFlow.SparkMLModel.train", false],
    ],
    "train_matcher() (in module matchflow)": [
      [2, "MatchFlow.train_matcher", false],
      [3, "MatchFlow.train_matcher", false],
    ],
    "trained_model (matchflow.mlmodel property)": [
      [2, "MatchFlow.MLModel.trained_model", false],
      [3, "MatchFlow.MLModel.trained_model", false],
    ],
    "trained_model (matchflow.sklearnmodel property)": [
      [2, "MatchFlow.SKLearnModel.trained_model", false],
      [3, "MatchFlow.SKLearnModel.trained_model", false],
    ],
    "trained_model (matchflow.sparkmlmodel property)": [
      [2, "MatchFlow.SparkMLModel.trained_model", false],
      [3, "MatchFlow.SparkMLModel.trained_model", false],
    ],
    "use_floats (matchflow.mlmodel attribute)": [
      [2, "MatchFlow.MLModel.use_floats", false],
      [3, "MatchFlow.MLModel.use_floats", false],
    ],
    "use_floats (matchflow.mlmodel property)": [
      [2, "id1", false],
      [3, "id1", false],
    ],
    "use_floats (matchflow.sklearnmodel property)": [
      [2, "MatchFlow.SKLearnModel.use_floats", false],
      [3, "MatchFlow.SKLearnModel.use_floats", false],
    ],
    "use_floats (matchflow.sparkmlmodel property)": [
      [2, "MatchFlow.SparkMLModel.use_floats", false],
      [3, "MatchFlow.SparkMLModel.use_floats", false],
    ],
    "use_vectors (matchflow.mlmodel attribute)": [
      [2, "MatchFlow.MLModel.use_vectors", false],
      [3, "MatchFlow.MLModel.use_vectors", false],
    ],
    "use_vectors (matchflow.mlmodel property)": [
      [2, "id2", false],
      [3, "id2", false],
    ],
    "use_vectors (matchflow.sklearnmodel property)": [
      [2, "MatchFlow.SKLearnModel.use_vectors", false],
      [3, "MatchFlow.SKLearnModel.use_vectors", false],
    ],
    "use_vectors (matchflow.sparkmlmodel property)": [
      [2, "MatchFlow.SparkMLModel.use_vectors", false],
      [3, "MatchFlow.SparkMLModel.use_vectors", false],
    ],
    "vectorize() (matchflow.vectorizer method)": [
      [2, "MatchFlow.Vectorizer.vectorize", false],
      [3, "MatchFlow.Vectorizer.vectorize", false],
    ],
    "vectorizer (class in matchflow)": [
      [2, "MatchFlow.Vectorizer", false],
      [3, "MatchFlow.Vectorizer", false],
    ],
    "webuilabeler (class in matchflow)": [
      [2, "MatchFlow.WebUILabeler", false],
      [3, "MatchFlow.WebUILabeler", false],
    ],
  },
  objects: {
    "": [[3, 0, 0, "-", "MatchFlow"]],
    MatchFlow: [
      [3, 1, 1, "", "CLILabeler"],
      [3, 1, 1, "", "CustomLabeler"],
      [3, 1, 1, "", "Feature"],
      [3, 1, 1, "", "GoldLabeler"],
      [3, 1, 1, "", "Labeler"],
      [3, 1, 1, "", "MLModel"],
      [3, 1, 1, "", "SKLearnModel"],
      [3, 1, 1, "", "SparkMLModel"],
      [3, 1, 1, "", "Tokenizer"],
      [3, 1, 1, "", "Vectorizer"],
      [3, 1, 1, "", "WebUILabeler"],
      [3, 4, 1, "", "apply_matcher"],
      [3, 4, 1, "", "create_features"],
      [3, 4, 1, "", "create_seeds"],
      [3, 4, 1, "", "down_sample"],
      [3, 4, 1, "", "featurize"],
      [3, 4, 1, "", "get_base_sim_functions"],
      [3, 4, 1, "", "get_base_tokenizers"],
      [3, 4, 1, "", "get_extra_tokenizers"],
      [3, 4, 1, "", "label_data"],
      [3, 4, 1, "", "label_pairs"],
      [3, 4, 1, "", "load_dataframe"],
      [3, 4, 1, "", "load_features"],
      [3, 4, 1, "", "save_dataframe"],
      [3, 4, 1, "", "save_features"],
      [3, 4, 1, "", "train_matcher"],
    ],
    "MatchFlow.CustomLabeler": [[3, 2, 1, "", "label_pair"]],
    "MatchFlow.Feature": [
      [3, 3, 1, "", "a_attr"],
      [3, 3, 1, "", "b_attr"],
      [3, 2, 1, "", "build"],
      [3, 2, 1, "", "preprocess"],
      [3, 2, 1, "", "preprocess_output_column"],
      [3, 2, 1, "", "template"],
    ],
    "MatchFlow.MLModel": [
      [3, 2, 1, "", "entropy"],
      [3, 3, 1, "id0", "nan_fill"],
      [3, 2, 1, "", "params_dict"],
      [3, 2, 1, "", "predict"],
      [3, 2, 1, "", "predict_with_confidence"],
      [3, 2, 1, "", "prediction_conf"],
      [3, 2, 1, "", "prep_fvs"],
      [3, 2, 1, "", "train"],
      [3, 3, 1, "", "trained_model"],
      [3, 3, 1, "id1", "use_floats"],
      [3, 3, 1, "id2", "use_vectors"],
    ],
    "MatchFlow.SKLearnModel": [
      [3, 2, 1, "", "cross_val_scores"],
      [3, 2, 1, "", "entropy"],
      [3, 2, 1, "", "get_model"],
      [3, 3, 1, "", "nan_fill"],
      [3, 2, 1, "", "params_dict"],
      [3, 2, 1, "", "predict"],
      [3, 2, 1, "", "predict_with_confidence"],
      [3, 2, 1, "", "prediction_conf"],
      [3, 2, 1, "", "train"],
      [3, 3, 1, "", "trained_model"],
      [3, 3, 1, "", "use_floats"],
      [3, 3, 1, "", "use_vectors"],
    ],
    "MatchFlow.SparkMLModel": [
      [3, 2, 1, "", "entropy"],
      [3, 2, 1, "", "get_model"],
      [3, 3, 1, "", "nan_fill"],
      [3, 2, 1, "", "params_dict"],
      [3, 2, 1, "", "predict"],
      [3, 2, 1, "", "predict_with_confidence"],
      [3, 2, 1, "", "prediction_conf"],
      [3, 2, 1, "", "train"],
      [3, 3, 1, "", "trained_model"],
      [3, 3, 1, "", "use_floats"],
      [3, 3, 1, "", "use_vectors"],
    ],
    "MatchFlow.Tokenizer": [
      [3, 2, 1, "", "out_col_name"],
      [3, 2, 1, "", "tokenize"],
      [3, 2, 1, "", "tokenize_set"],
      [3, 2, 1, "", "tokenize_spark"],
    ],
    "MatchFlow.Vectorizer": [
      [3, 2, 1, "", "build_from_doc_freqs"],
      [3, 2, 1, "", "init"],
      [3, 2, 1, "", "out_col_name"],
      [3, 2, 1, "", "vectorize"],
    ],
  },
  objnames: {
    0: ["py", "module", "Python module"],
    1: ["py", "class", "Python class"],
    2: ["py", "method", "Python method"],
    3: ["py", "property", "Python property"],
    4: ["py", "function", "Python function"],
  },
  objtypes: {
    0: "py:module",
    1: "py:class",
    2: "py:method",
    3: "py:property",
    4: "py:function",
  },
  terms: {
    "": [2, 3],
    0: [2, 3],
    1: [2, 3],
    10: [2, 3],
    1000: [2, 3],
    127: [2, 3],
    3: [2, 3],
    "3gram": [2, 3],
    5: [2, 3],
    5005: [2, 3],
    8501: [2, 3],
    A: [2, 3],
    For: [2, 3],
    If: [2, 3],
    It: [2, 3],
    The: [2, 3],
    _id: [2, 3],
    a_attr: [2, 3],
    a_col: [2, 3],
    a_df: [2, 3],
    abc: [2, 3],
    abstract: [2, 3],
    abstractmethod: [2, 3],
    activ: [2, 3],
    ad: [2, 3],
    addit: [2, 3],
    all: [2, 3],
    alphanumerictoken: [2, 3],
    an: [2, 3],
    ani: [2, 3],
    appli: [2, 3],
    apply_match: [2, 3],
    ar: [2, 3],
    argument: [2, 3],
    arrai: [2, 3],
    assign: [2, 3],
    attribut: [2, 3],
    automat: [2, 3],
    b: [2, 3],
    b_attr: [2, 3],
    b_col: [2, 3],
    b_df: [2, 3],
    bag: [2, 3],
    base: [2, 3],
    baseestim: [2, 3],
    batch: [2, 3],
    batch_siz: [2, 3],
    befor: [2, 3],
    being: [2, 3],
    between: [2, 3],
    bool: [2, 3],
    both: [2, 3],
    bucket: [2, 3],
    bucket_s: [2, 3],
    build: [2, 3],
    build_from_doc_freq: [2, 3],
    cach: [2, 3],
    calcul: [2, 3],
    call: [2, 3],
    callabl: [2, 3],
    candid: [2, 3],
    certain: [2, 3],
    class: [2, 3],
    classmethod: [2, 3],
    cli: [2, 3],
    clilabel: [2, 3],
    column: [2, 3],
    comput: [2, 3],
    confid: [2, 3],
    confidence_col: [2, 3],
    configur: [2, 3],
    consid: [2, 3],
    consist: [2, 3],
    constructor: [2, 3],
    contain: [2, 3],
    continu: [2, 3],
    continuousentropyactivelearn: [2, 3],
    convers: [2, 3],
    convert: [2, 3],
    correl: [2, 3],
    correspond: [2, 3],
    cosinefeatur: [2, 3],
    could: [2, 3],
    count: [2, 3],
    creat: [2, 3],
    create_featur: [2, 3],
    create_se: [2, 3],
    cross_val_scor: [2, 3],
    current: [2, 3],
    custom: [2, 3],
    customlabel: [2, 3],
    cv: [2, 3],
    data: [2, 3],
    datafram: [2, 3],
    dataset: [2, 3],
    dedup: [2, 3],
    default: [2, 3],
    defin: [2, 3],
    deseri: [2, 3],
    detect: [2, 3],
    df: [2, 3],
    df_type: [2, 3],
    dict: [2, 3],
    dictionari: [2, 3],
    disk: [2, 3],
    doc_freq: [2, 3],
    done: [2, 3],
    down: [2, 3],
    down_sampl: [2, 3],
    downsampl: [2, 3],
    drop: [2, 3],
    e: [2, 3],
    each: [2, 3],
    effeci: [2, 3],
    effici: [2, 3],
    either: [2, 3],
    entiti: [2, 3],
    entropi: [2, 3],
    entropyactivelearn: [2, 3],
    estim: [2, 3],
    exampl: [2, 3],
    expect: [2, 3],
    express: [2, 3],
    extra: [2, 3],
    extratoken: [2, 3],
    fals: [2, 3],
    featur: [2, 3],
    feature_col: [2, 3],
    feature_vector: [2, 3],
    file: [2, 3],
    fill: [2, 3],
    fill_na: [2, 3],
    first: [2, 3],
    flask_host: [2, 3],
    flask_port: [2, 3],
    float: [2, 3],
    float32: [2, 3],
    float64: [2, 3],
    follow: [2, 3],
    for_table_a: [2, 3],
    format: [2, 3],
    from: [2, 3],
    function: [2, 3],
    fv: [2, 3],
    g: [2, 3],
    gener: [2, 3],
    get: [2, 3],
    get_base_sim_funct: [2, 3],
    get_base_token: [2, 3],
    get_extra_token: [2, 3],
    get_model: [2, 3],
    give: [2, 3],
    given: [2, 3],
    gold: [2, 3],
    goldlabel: [2, 3],
    guarente: [2, 3],
    handl: [2, 3],
    have: [2, 3],
    i: [2, 3],
    id: [2, 3],
    id1: [2, 3],
    id2: [2, 3],
    id_col: [2, 3],
    identifi: [2, 3],
    implement: [2, 3],
    includ: [2, 3],
    index: 0,
    init: [2, 3],
    initi: [2, 3],
    input: [2, 3],
    input_col: [2, 3],
    instanc: [2, 3],
    int: [2, 3],
    interfac: [2, 3],
    is_table_a: [2, 3],
    jaccardfeatur: [2, 3],
    keyword: [2, 3],
    kwarg: [2, 3],
    label: [2, 3],
    label_col: [2, 3],
    label_column: [2, 3],
    label_data: [2, 3],
    label_pair: [2, 3],
    labeled_data: [2, 3],
    learn: [2, 3],
    learner: [2, 3],
    learner_kwarg: [2, 3],
    list: [2, 3],
    liter: [2, 3],
    load: [2, 3],
    load_datafram: [2, 3],
    load_featur: [2, 3],
    machin: [2, 3],
    mai: [2, 3],
    make: [2, 3],
    manag: [2, 3],
    match: [2, 3],
    matcher: [2, 3],
    max_it: [2, 3],
    max_label: [2, 3],
    metadata: [2, 3],
    method: [2, 3],
    miss: [2, 3],
    ml: [2, 3],
    mlmodel: [2, 3],
    mode: [2, 3],
    model: [2, 3],
    model_arg: [2, 3],
    modul: 0,
    more: [2, 3],
    must: [2, 3],
    name: [2, 3],
    nan: [2, 3],
    nan_fil: [2, 3],
    need: [2, 3],
    none: [2, 3],
    note: [2, 3],
    nseed: [2, 3],
    null: [2, 3],
    null_threshold: [2, 3],
    number: [2, 3],
    numerictoken: [2, 3],
    object: [2, 3],
    on_demand_stop: [2, 3],
    option: [2, 3],
    order: [2, 3],
    other: [2, 3],
    otherwis: [2, 3],
    out_col_nam: [2, 3],
    output: [2, 3],
    output_col: [2, 3],
    over: [2, 3],
    overlapcoefffeatur: [2, 3],
    packag: [2, 3],
    page: 0,
    pair: [2, 3],
    panda: [2, 3],
    paramet: [2, 3],
    params_dict: [2, 3],
    parquet: [2, 3],
    parquet_file_path: [2, 3],
    partit: [2, 3],
    pass: [2, 3],
    path: [2, 3],
    pd: [2, 3],
    percent: [2, 3],
    pickl: [2, 3],
    portion: [2, 3],
    posit: [2, 3],
    possibl: [2, 3],
    potenti: [2, 3],
    precis: [2, 3],
    predict: [2, 3],
    predict_with_confid: [2, 3],
    prediction_col: [2, 3],
    prediction_conf: [2, 3],
    prep_fv: [2, 3],
    prepar: [2, 3],
    preprocess: [2, 3],
    preprocess_output_column: [2, 3],
    previou: [2, 3],
    probabl: [2, 3],
    produc: [2, 3],
    properti: [2, 3],
    provid: [2, 3],
    pyspark: [2, 3],
    qgramtoken: [2, 3],
    queue_siz: [2, 3],
    record: [2, 3],
    request: [2, 3],
    requir: [2, 3],
    result: [2, 3],
    return: [2, 3],
    row: [2, 3],
    row1: [2, 3],
    row2: [2, 3],
    same: [2, 3],
    sampl: [2, 3],
    save: [2, 3],
    save_datafram: [2, 3],
    save_featur: [2, 3],
    schema: [2, 3],
    scikit: [2, 3],
    score: [2, 3],
    score_column: [2, 3],
    search: 0,
    search_id_column: [2, 3],
    second: [2, 3],
    see: [2, 3],
    seed: [2, 3],
    self: [2, 3],
    separ: [2, 3],
    serial: [2, 3],
    set: [2, 3],
    should: [2, 3],
    siffeatur: [2, 3],
    sim_funct: [2, 3],
    similar: [2, 3],
    singl: [2, 3],
    size: [2, 3],
    sklearn: [2, 3],
    sklearnmodel: [2, 3],
    sourc: [2, 3],
    spark: [2, 3],
    sparkdatafram: [2, 3],
    sparkdf: [2, 3],
    sparkmlmodel: [2, 3],
    specifi: [2, 3],
    sql: [2, 3],
    start: [2, 3],
    store: [2, 3],
    str: [2, 3],
    streamlit_port: [2, 3],
    string: [2, 3],
    strippedqgramtoken: [2, 3],
    strippedwhitespacetoken: [2, 3],
    tabl: [2, 3],
    techniqu: [2, 3],
    templat: [2, 3],
    tfidffeatur: [2, 3],
    than: [2, 3],
    thei: [2, 3],
    thi: [2, 3],
    token: [2, 3],
    tokenize_set: [2, 3],
    tokenize_spark: [2, 3],
    tool: [2, 3],
    toolkit: [2, 3],
    train: [2, 3],
    train_match: [2, 3],
    trained_model: [2, 3],
    true: [2, 3],
    tupl: [2, 3],
    type: [2, 3],
    union: [2, 3],
    uniqu: [2, 3],
    us: [2, 3],
    use_float: [2, 3],
    use_vector: [2, 3],
    valu: [2, 3],
    variou: [2, 3],
    vector: [2, 3],
    vector_col: [2, 3],
    want: [2, 3],
    web: [2, 3],
    webuilabel: [2, 3],
    welcom: 0,
    when: [2, 3],
    where: [2, 3],
    whether: [2, 3],
    which: [2, 3],
    without: [2, 3],
    wrap: [2, 3],
    wrapper: [2, 3],
    you: [2, 3],
    your: [2, 3],
  },
  titles: [
    "MatchFlow Tools Documentation",
    "Module Index",
    "MatchFlow",
    "MatchFlow",
  ],
  titleterms: {
    content: 0,
    document: 0,
    index: 1,
    indic: 0,
    matchflow: [0, 2, 3],
    modul: 1,
    tabl: 0,
    tool: 0,
  },
});
